# Generated by Django 5.0.3 on 2024-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0031_rename_sub_category_products_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="films.subcategories"),
        ),
        migrations.AlterField(
            model_name="products",
            name="tags",
            field=models.ManyToManyField(blank=True, to="films.tag"),
        ),
    ]
