# Generated by Django 5.0.3 on 2024-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0032_alter_products_subcategories_alter_products_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Телеграмм номер"
            ),
        ),
    ]
