# Generated by Django 5.0.3 on 2024-03-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0033_alter_products_telegram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="product-images/default.jpg", upload_to="product-images"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="films.products"
                    ),
                ),
            ],
        ),
    ]
