# Generated by Django 4.2.2 on 2024-04-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0034_remove_products_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategories",
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
            },
        ),
        migrations.RemoveField(
            model_name="categories",
            name="name",
        ),
        migrations.RemoveField(
            model_name="products",
            name="email",
        ),
        migrations.RemoveField(
            model_name="subcategories",
            name="category",
        ),
        migrations.RemoveField(
            model_name="subcategories",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="categories",
            name="name_en",
            field=models.CharField(
                default="", max_length=50, verbose_name="Category (English)"
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_ru",
            field=models.CharField(
                default="", max_length=50, verbose_name="Категория (Русский)"
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_uz",
            field=models.CharField(
                default="", max_length=50, verbose_name="Kategoriya (O'zbek)"
            ),
        ),
        migrations.AddField(
            model_name="subcategories",
            name="name_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Subcategory (English)"
            ),
        ),
        migrations.AddField(
            model_name="subcategories",
            name="name_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Подкатегория (Русский)"
            ),
        ),
        migrations.AddField(
            model_name="subcategories",
            name="name_uz",
            field=models.CharField(
                default="", max_length=100, verbose_name="Subkategoriya (O'zbek)"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                verbose_name="Tag Name (English)",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ru",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                verbose_name="Имя тега (Русский)",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_uz",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                verbose_name="Tag nomi (O'zbek)",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Телеграмм номер"
            ),
        ),
        migrations.CreateModel(
            name="TagSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="films.subcategories",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag__subcategory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory_tags",
                        to="films.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="films.categories",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag__category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_tags",
                        to="films.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="films.categories",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="films.subcategories",
                    ),
                ),
            ],
        ),
    ]
