# Generated by Django 4.2.2 on 2024-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0035_alter_categories_options_alter_subcategories_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategories",
            name="is_linked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_linked",
            field=models.BooleanField(default=False),
        ),
    ]
