# Generated by Django 4.2.2 on 2023-10-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_films_description'),
        ('accounts', '0012_user_name_alter_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='user',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_category', to='films.categories'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='films.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_category', to='films.categories'),
        ),
    ]
