# Generated by Django 4.2.2 on 2023-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_films_description'),
        ('accounts', '0013_remove_user_subcategory_user_sub_category_user_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_business_account',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='films.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
