# Generated by Django 4.2.2 on 2023-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_name_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_maps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
