# Generated by Django 4.2.2 on 2023-10-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_films_description'),
        ('accounts', '0016_user_url_maps_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_category', to='films.subcategories'),
        ),
    ]
