# Generated by Django 4.2.2 on 2023-10-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_films_description'),
        ('accounts', '0017_alter_user_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.country'),
        ),
    ]
