# Generated by Django 4.2.2 on 2023-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ball',
            field=models.IntegerField(default=100),
        ),
    ]
