# Generated by Django 4.2.2 on 2023-10-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_top_film',
            field=models.BooleanField(default=False),
        ),
    ]
