# Generated by Django 4.2.2 on 2023-10-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_is_top_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_top_film',
        ),
    ]
