# Generated by Django 4.2.7 on 2024-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_pointstransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="previous_ball",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
