# Generated by Django 4.2.7 on 2024-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_user_previous_ball"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_business_account",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
