# Generated by Django 4.2.7 on 2024-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0033_alter_user_is_business_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="previous_ball",
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.DecimalField(decimal_places=3, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="previous_currency",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
