# Generated by Django 4.2.7 on 2024-01-31 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_remove_user_previous_ball_user_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ball",
        ),
    ]
