# Generated by Django 5.0.3 on 2024-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0037_alter_user_is_business_account_alter_user_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_business_account",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
